### ISSUE TITLE
[BUG] prowlarr:latest does not use PUID and PGID from environment

### ISSUE THREAD

**Issue by lordpayder** [linuxserver/docker-prowlarr#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Starting a container with the following docker-compose definition fails, because the application process does not use the provided PUID.
```
prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1200
      - PGID=1200
    volumes:
      - ./prowlarr/config:/config
```

### Expected Behavior

The application process should use the user with provided PUID and GUID.

### Steps To Reproduce

- copy & paste above provided content into docker-compose.yml
- mkdir -p prowlarr/config
- chown 1200:1200 prowlarr/config
- docker-compose up -d
- docker-compose logs (see error)
- docker-compose exec prowlarr bash
- ps aux (application process running with user 911)

### Environment

```markdown
- OS: Ubuntu 20.04
- How docker service was installed: From docker repo
```

### CPU architecture

x86-64

### Docker creation

```bash
prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1200
      - PGID=1200
    volumes:
      - ./prowlarr/config:/config
```
docker-compose up -d
```


### Container logs

```bash
prowlarr_1  | [migrations] started
prowlarr_1  | [migrations] no migrations found
prowlarr_1  | 
prowlarr_1  | -------------------------------------
prowlarr_1  |           _         ()
prowlarr_1  |          | |  ___   _    __
prowlarr_1  |          | | / __| | |  /  \
prowlarr_1  |          | | \__ \ | | | () |
prowlarr_1  |          |_| |___/ |_|  \__/
prowlarr_1  | 
prowlarr_1  | 
prowlarr_1  | Brought to you by linuxserver.io
prowlarr_1  | -------------------------------------
prowlarr_1  | 
prowlarr_1  | To support the app dev(s) visit:
prowlarr_1  | Prowlarr: https://opencollective.com/prowlarr
prowlarr_1  | 
prowlarr_1  | To support LSIO projects visit:
prowlarr_1  | https://www.linuxserver.io/donate/
prowlarr_1  | -------------------------------------
prowlarr_1  | GID/UID
prowlarr_1  | -------------------------------------
prowlarr_1  | 
prowlarr_1  | User uid:    1200
prowlarr_1  | User gid:    1200
prowlarr_1  | -------------------------------------
prowlarr_1  | 
prowlarr_1  | [custom-init] No custom files found, skipping...
prowlarr_1  | [Info] Bootstrap: Starting Prowlarr - /app/prowlarr/bin/Prowlarr - Version 1.0.1.2220 
prowlarr_1  | [Info] AppFolderInfo: Data directory is being overridden to [/config] 
prowlarr_1  | [Debug] Bootstrap: Console selected 
prowlarr_1  | [Info] AppFolderInfo: Data directory is being overridden to [/config] 
prowlarr_1  | [Info] AppFolderInfo: Data directory is being overridden to [/config] 
prowlarr_1  | [Error] Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider: An error occurred while reading the key ring. 
prowlarr_1  | 
prowlarr_1  | [v1.0.1.2220] System.UnauthorizedAccessException: Access to the path '/config/asp' is denied.
prowlarr_1  |  ---> System.IO.IOException: Permission denied
prowlarr_1  |    --- End of inner exception stack trace ---
prowlarr_1  |    at System.IO.FileSystem.CreateDirectory(String fullPath)
prowlarr_1  |    at System.IO.DirectoryInfo.Create()
prowlarr_1  |    at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext()
prowlarr_1  |    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
prowlarr_1  |    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
prowlarr_1  |    at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements()
prowlarr_1  |    at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
prowlarr_1  |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
prowlarr_1  |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
prowlarr_1  |    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
prowlarr_1  | 
prowlarr_1  | 
prowlarr_1  | [Trace] DiskProviderBase: Directory '/config' isn't writable. Access to the path '/config/prowlarr_write_test.txt' is denied. 
prowlarr_1  | [Fatal] Microsoft.AspNetCore.Hosting.Diagnostics: Application startup exception 
prowlarr_1  | 
prowlarr_1  | [v1.0.1.2220] NzbDrone.Common.Exceptions.ProwlarrStartupException: Prowlarr failed to start: AppFolder /config is not writable
prowlarr_1  |    at NzbDrone.Common.EnvironmentInfo.AppFolderFactory.Register() in D:\a\1\s\src\NzbDrone.Common\EnvironmentInfo\AppFolderFactory.cs:line 58
prowlarr_1  |    at NzbDrone.Host.Startup.Configure(IApplicationBuilder app, IStartupContext startupContext, Lazy`1 mainDatabaseFactory, Lazy`1 logDatabaseFactory, DatabaseTarget dbTarget, ISingleInstancePolicy singleInstancePolicy, InitializeLogger initializeLogger, ReconfigureLogging reconfigureLogging, IAppFolderFactory appFolderFactory, IProvidePidFile pidFileProvider, IConfigFileProvider configFileProvider, IRuntimeInfo runtimeInfo, IFirewallAdapter firewallAdapter, IEventAggregator eventAggregator, ProwlarrErrorPipeline errorHandler) in D:\a\1\s\src\NzbDrone.Host\Startup.cs:line 225
prowlarr_1  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
prowlarr_1  |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
prowlarr_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
prowlarr_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
prowlarr_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
prowlarr_1  |    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
prowlarr_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
prowlarr_1  | 
prowlarr_1  | 
prowlarr_1  | 
prowlarr_1  | 
prowlarr_1  | [Fatal] ConsoleApp: EPIC FAIL! 
prowlarr_1  | 
prowlarr_1  | [v1.0.1.2220] NzbDrone.Common.Exceptions.ProwlarrStartupException: Prowlarr failed to start: AppFolder /config is not writable
prowlarr_1  |    at NzbDrone.Common.EnvironmentInfo.AppFolderFactory.Register() in D:\a\1\s\src\NzbDrone.Common\EnvironmentInfo\AppFolderFactory.cs:line 58
prowlarr_1  |    at NzbDrone.Host.Startup.Configure(IApplicationBuilder app, IStartupContext startupContext, Lazy`1 mainDatabaseFactory, Lazy`1 logDatabaseFactory, DatabaseTarget dbTarget, ISingleInstancePolicy singleInstancePolicy, InitializeLogger initializeLogger, ReconfigureLogging reconfigureLogging, IAppFolderFactory appFolderFactory, IProvidePidFile pidFileProvider, IConfigFileProvider configFileProvider, IRuntimeInfo runtimeInfo, IFirewallAdapter firewallAdapter, IEventAggregator eventAggregator, ProwlarrErrorPipeline errorHandler) in D:\a\1\s\src\NzbDrone.Host\Startup.cs:line 225
prowlarr_1  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
prowlarr_1  |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
prowlarr_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
prowlarr_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
prowlarr_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
prowlarr_1  |    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
prowlarr_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
prowlarr_1  |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
prowlarr_1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
prowlarr_1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
prowlarr_1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
prowlarr_1  |    at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in D:\a\1\s\src\NzbDrone.Host\Bootstrap.cs:line 83
prowlarr_1  |    at NzbDrone.Console.ConsoleApp.Main(String[] args) in D:\a\1\s\src\NzbDrone.Console\ConsoleApp.cs:line 43
prowlarr_1  | 
prowlarr_1  | 
prowlarr_1  | Press enter to exit...
prowlarr_1  | Non-recoverable failure, waiting for user intervention...
```

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-prowlarr/blob/main/root/etc/s6-overlay/s6-rc.d/svc-prowlarr/run#L6
```
prowlarr_1  | User uid:    1200
prowlarr_1  | User gid:    1200
```

My guess is you have multiple continers and you're confusing them since your compose doesn't set a container name

**Comment by lordpayder** [comment]
I only have 1 container running, so I'm for sure not confusing anything.
also i used docker-compose logs, and there's only one service defined.

There is a user generated with PUID and GUID 1200 called "abc", but it's not used for the application.

**Comment by lordpayder** [comment]
![image](https://user-images.githubusercontent.com/76409640/210426269-c653bb41-b3b2-4685-85a4-b6e9616d1511.png)

**Comment by aptalca** [comment]
oh, I see it. The service file is missing the dependency so it's starting the app before the abc user's id is changed to `PUID`

@Roxedus
