### ISSUE TITLE
[BUG] 1.17.2.4511-ls70 [Fatal] ConsoleApp: EPIC FAIL!

### ISSUE THREAD

**Issue by Berry-95** [linuxserver/docker-prowlarr#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running latest version results in a ConsoleApp: EPIC FAIL! loop.

### Expected Behavior

Running previous version _1.17.2.4511-ls69_ results in successful startup
`docker run -d \
  --name=prowlarr \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -p 9696:9696 \
  -v ./data:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/prowlarr:1.17.2.4511-ls69`

Docker log:
```
...
[Info] Microsoft.Hosting.Lifetime: Now listening on: http://[::]:9696
[Info] UpdaterConfigProvider: Update mechanism BuiltIn not supported in the current configuration, changing to Docker.
[Info] AppSyncProfileService: Setting up default app profile
[ls.io-init] done.
[Info] CommandExecutor: Starting 3 threads for tasks.
[Info] ManagedHttpDispatcher: IPv4 is available: True, IPv6 will be disabled
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down.
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production
[Info] Microsoft.Hosting.Lifetime: Content root path: /app/prowlarr/bin
```

### Steps To Reproduce

- Use the provided docker run
  - Fails both with or without the volume argument (so don't think it's my config)
- Then `docker logs prowlarr`

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS x86_64
- How docker service was installed: I think using https://get.docker.com
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name=prowlarr \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -p 9696:9696 \
  -v ./data:/config \
  --restart unless-stopped \
  lscr.io/linuxserver/prowlarr:latest
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Prowlarr: https://opencollective.com/prowlarr

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
failed to load external entity "/config/config.xml"
[Info] Bootstrap: Starting Prowlarr - /app/prowlarr/bin/Prowlarr - Version 1.17.2.4511
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Debug] Bootstrap: Console selected
[Info] AppFolderInfo: Data directory is being overridden to [/config]


[Fatal] ConsoleApp: EPIC FAIL!

[v1.17.2.4511] System.TypeLoadException: Method 'AddScheme' in type 'Microsoft.AspNetCore.Authentication.AuthenticationSchemeProvider' from assembly 'Microsoft.AspNetCore.Authentication.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at Microsoft.Extensions.DependencyInjection.AuthenticationCoreServiceCollectionExtensions.AddAuthenticationCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreMvcCoreBuilderExtensions.AddAuthorizationServices(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreMvcCoreBuilderExtensions.AddAuthorization(IMvcCoreBuilder builder)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllers(IServiceCollection services, Action`1 configure)
   at NzbDrone.Host.Startup.ConfigureServices(IServiceCollection services) in ./Prowlarr.Host/Startup.cs:line 85
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in ./Prowlarr.Host/Bootstrap.cs:line 80
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in ./Prowlarr.Console/ConsoleApp.cs:line 43


Press enter to exit...
```
```

**Comment by Roxedus** [comment]
Post some hardware information

**Comment by andrewgdunn** [comment]
@Berry-95 what builds did you find to be working? I'm trying to understand why I'm getting http timeouts with readarr and prowlarr and the upstream discussion suspects a ".net networking issue". Wondering if a previous version is known to be working.

https://github.com/Prowlarr/Prowlarr/issues/1992
